### ISSUE TITLE
PaddleNLP/applications/neural_search/recall/in_batch_negative/deploy/python/config_nlp.yml 启动tensorrt加速，发现没有效果

### ISSUE THREAD

**Issue by AI-Mart** [PaddlePaddle/PaddleNLP#1683]
![image](https://user-images.githubusercontent.com/63343847/154183622-f1485ca2-47d8-4efd-aec9-9ca307f75524.png)
如题，配置加速后，实际运行没有提速效果，是否还需要安装其他包？
centos7 python3.7

astor                     0.8.1
Babel                     2.9.1
bce-python-sdk            0.8.64
cached-property           1.5.2
certifi                   2021.10.8
cfgv                      3.3.1
charset-normalizer        2.0.12
click                     7.1.2
colorama                  0.4.4
colorlog                  6.6.0
cycler                    0.11.0
decorator                 5.1.1
dill                      0.3.4
distlib                   0.3.4
filelock                  3.4.2
flake8                    4.0.1
Flask                     1.1.4
Flask-Babel               2.0.0
fonttools                 4.29.1
func-timeout              4.3.5
future                    0.18.2
grpcio                    1.33.2
grpcio-tools              1.33.2
h5py                      3.6.0
hnswlib                   0.6.1
identify                  2.4.9
idna                      3.3
importlib-metadata        4.2.0
itsdangerous              1.1.0
jieba                     0.42.1
Jinja2                    2.11.3
joblib                    1.1.0
kiwisolver                1.3.2
MarkupSafe                1.1.1
matplotlib                3.5.1
mccabe                    0.6.1
multiprocess              0.70.12.2
nodeenv                   1.6.0
numpy                     1.21.5
opencv-python             4.2.0.32
packaging                 21.3
paddle-serving-app        0.7.0
paddle-serving-client     0.7.0
paddle-serving-server-gpu 0.7.0.post1028
paddlenlp                 2.2.4
paddlepaddle-gpu          0.0.0.post101
pandas                    0.25.1
Pillow                    9.0.1
pip                       21.3.1
platformdirs              2.5.0
pre-commit                2.17.0
protobuf                  3.19.4
pybind11                  2.9.1
pyclipper                 1.3.0.post2
pycodestyle               2.8.0
pycryptodome              3.14.1
pyflakes                  2.4.0
pymilvus                  1.1.2
pyparsing                 3.0.7
python-dateutil           2.8.2
pytz                      2021.3
PyYAML                    6.0
requests                  2.27.1
scikit-learn              1.0.2
scipy                     1.7.3
sentencepiece             0.1.92
seqeval                   1.2.2
setuptools                60.5.0
Shapely                   1.8.0
shellcheck-py             0.8.0.4
six                       1.16.0
threadpoolctl             3.1.0
toml                      0.10.2
tqdm                      4.62.3
typing_extensions         4.1.0
ujson                     5.1.0
urllib3                   1.26.8
virtualenv                20.13.1
visualdl                  2.2.3
Werkzeug                  1.0.1
wheel                     0.37.1
zipp                      3.7.0

**Comment by AI-Mart** [comment]
cuda10.1,cudnn 7.6.5
开启gpu预测，启动服务端python web_service.py, 启动客户端python  rpc_client.py 预测返回时间25ms左右
开启tensorrt,启动服务端python web_service.py, 启动客户端python  rpc_client.py 预测返回时间也是25ms左右
说明tensorrt没有启动对gpu的加速，请教是什么原因？
tensorrt底层安装，参考链接https://blog.csdn.net/qq_15821487/article/details/122952282，已经安装成功

**Comment by AI-Mart** [comment]
python 3.7,4
gcc version 8.5.0 (GCC) 
TensorRT-6.0.1.5
已经安装，
![image](https://user-images.githubusercontent.com/63343847/154224553-cbecaee6-ff78-4ea2-9b15-b3e845e25754.png)
tensor rt还是没有加速，是否是gcc 8.5版本必须降级成8.2才行呢

**Comment by TeslaZhao** [comment]
开启ir_optim: True

参考：
https://github.com/PaddlePaddle/Serving/blob/v0.7.0/examples/Pipeline/PaddleOCR/ocr/config.yml

**Comment by AI-Mart** [comment]
感谢回复，有两个问题：
第一个：这个config_nlp.yml配置文件，有没有最完整的官方配置参数说明，需要什么参数自己可以参照官方说明往上面添加参数，因为这个案例的config_nlp.yml配置文件是没有ir_optim这个参数的，后续可能还需要其他参数，能否提供个完整参数说明链接。
第二个：我刚才添加了参数ir_optim: True，运行python web_service.py发现程序卡主了，应该是报错了，是什么原因呢
![image](https://user-images.githubusercontent.com/63343847/154230502-afa2e0a7-1023-4b30-a02e-8e7facdd090e.png)

**Comment by AI-Mart** [comment]
现在已经把gcc降级为8.2了和官方paddle安装包完全匹配了，不添加了参数ir_optim: True，运行正常，但tensorrt没有加速效果。添加参数ir_optim: True运行报错
`E0216 17:04:09.163729 30082 helper.h:111] Parameter check failed at: ../builder/Network.cpp::addInput::671, condition: isValidDims(dims, hasImplicitBatchDimension())`

**Comment by TeslaZhao** [comment]
https://github.com/PaddlePaddle/Serving/blob/v0.7.0/doc/Serving_Configure_CN.md#python-pipeline
完整参数信息看此文档

另外，看下PipelineServingLogs/pipeline.log.wf，所有错误信息都在这里

**Comment by AI-Mart** [comment]
感谢提供的完整文档
报错信息
```
CRITICAL 2022-02-16 19:29:49,479 [operator.py:1315] [ernie|0] failed to init op: (InvalidArgument) Adding input reshape2_60.tmp_0 failed in TensorRT inference network. Please recheck your input.
  [Hint: input should not be null.] (at /paddle/paddle/fluid/inference/tensorrt/engine.cc:266)
Traceback (most recent call last):
  File "/data/mart/neural_search/venv/lib/python3.7/site-packages/paddle_serving_server/pipeline/operator.py", line 1308, in _run
    concurrency_idx)
  File "/data/mart/neural_search/venv/lib/python3.7/site-packages/paddle_serving_server/pipeline/local_service_handler.py", line 228, in get_client
    mkldnn_bf16_op_list=self._mkldnn_bf16_op_list)
  File "/data/mart/neural_search/venv/lib/python3.7/site-packages/paddle_serving_app/local_predict.py", line 235, in load_model_config
    self.predictor = paddle_infer.create_predictor(config)
ValueError: (InvalidArgument) Adding input reshape2_60.tmp_0 failed in TensorRT inference network. Please recheck your input.
  [Hint: input should not be null.] (at /paddle/paddle/fluid/inference/tensorrt/engine.cc:266)

```

**Comment by TeslaZhao** [comment]
请加一下Paddle Serving微信群，我们在群里高效沟通
![image](https://user-images.githubusercontent.com/6309021/154259343-95a801ff-c236-4030-92a0-4fa36b1760ab.png)

**Comment by AI-Mart** [comment]
已添加

**Comment by AI-Mart** [comment]
你好，麻烦有空的时候回复下微信群信息哈，我已经做了单边测试是正常的，部署pipeline服务就不正常，我怀疑是不是配置文件缺少feed_list的参数，但是我看官方参数配置没有这个

报错也是提示，feed是空的

**Comment by w5688414** [comment]
检查一下TensorRT是否安装正确：
https://paddleinference.paddlepaddle.org.cn/master/user_guides/download_lib.html#python
https://github.com/PaddlePaddle/Serving/blob/v0.7.0/tools/dockerfiles/build_scripts/install_trt.sh

![image](https://user-images.githubusercontent.com/12107462/154633046-27a7ebd3-1519-49ec-b57a-1c68295b0b23.png)

**Comment by AI-Mart** [comment]
因为实际部署都是docker部署，我用docker安装了下服务，dockerfile内容如下：
```
FROM registry.baidubce.com/paddlepaddle/serving:0.7.0-cuda10.1-cudnn7-devel

COPY . /deploy
WORKDIR /deploy

# Install Python3.7
RUN mkdir -p /root/python_build/ && \
    tar -zxf sqlite-autoconf-3250300.tar.gz && cd sqlite-autoconf-3250300 && \
    ./configure -prefix=/usr/local && make -j8 && make install && cd ../ && rm sqlite-autoconf-3250300.tar.gz

# Install Python3.7
RUN tar -xzf Python-3.7.4.tgz && cd Python-3.7.4 && \
    CFLAGS="-Wformat" ./configure --prefix=/usr/local/ --enable-shared > /dev/null && \
    make -j8 > /dev/null && make altinstall > /dev/null && ldconfig && cd .. && rm -rf Python-3.7.4*

ENV LD_LIBRARY_PATH=/usr/local/lib:${LD_LIBRARY_PATH}

RUN rm -rf /usr/local/bin/python3 && rm -rf /usr/bin/python3
RUN ln -sf /usr/local/bin/python3.7 /usr/local/bin/python3 && ln -sf /usr/local/bin/python3.7 /usr/bin/python3 && ln -sf /usr/local/bin/pip3.7 /usr/local/bin/pip3 && ln -sf /usr/local/bin/pip3.7 /usr/bin/pip3

RUN rm -r /root/python_build

# Install TensorRT6
RUN tar -zxf TensorRT6-cuda10.1-cudnn7.tar.gz -C /usr/local \
    && cp -rf /usr/local/TensorRT6-cuda10.1-cudnn7/include/* /usr/include/ && cp -rf /usr/local/TensorRT6-cuda10.1-cudnn7/lib/* /usr/lib/ \
    && echo "cuda10.1 trt install ==============>>>>>>>>>>>>" \
    && pip3 install /usr/local/TensorRT6-cuda10.1-cudnn7/python/tensorrt-6.0.1.5-cp37-none-linux_x86_64.whl \
    && pip3 install /usr/local/TensorRT6-cuda10.1-cudnn7/graphsurgeon/graphsurgeon-0.4.1-py2.py3-none-any.whl \
    && rm TensorRT6-cuda10.1-cudnn7.tar.gz

# Install requirements
RUN pip config set global.index-url https://mirror.baidu.com/pypi/simple \
    && python3.7 -m pip install --upgrade setuptools \
    && python3.7 -m pip install --upgrade pip \
    && pip3 install -r requirements.txt \
    && pip3 install paddlepaddle_gpu-2.2.2.post101-cp37-cp37m-linux_x86_64.whl  \
    && rm paddlepaddle_gpu-2.2.2.post101-cp37-cp37m-linux_x86_64.whl \
    && python3 paddle_model.py

ENTRYPOINT python3 web_service.py


```
配置文件如下：
```
# worker_num, 最大并发数。当build_dag_each_worker=True时, 框架会创建worker_num个进程，每个进程内构建grpcSever和DAG
# 当build_dag_each_worker=False时，框架会设置主线程grpc线程池的max_workers=worker_num
worker_num: 20
# build_dag_each_worker, False，框架在进程内创建一条DAG；True，框架会每个进程内创建多个独立的DAG
build_dag_each_worker: false

dag:
  # op资源类型, True, 为线程模型；False，为进程模型
  is_thread_op: False
  # 使用性能分析, True，生成Timeline性能数据，对性能有一定影响；False为不使用
  tracer:
    interval_s: 10
# http端口, rpc_port和http_port不允许同时为空。当rpc_port可用且http_port为空时，不自动生成http_port
http_port: 18082
# rpc端口, rpc_port和http_port不允许同时为空。当rpc_port为空且http_port不为空时，会自动将rpc_port设置为http_port+1
rpc_port: 8080
op:
  ernie:
    # 并发数，is_thread_op=True时，为线程并发；否则为进程并发
    concurrency: 1
    # 当op配置没有server_endpoints时，从local_service_conf读取本地服务配置
    local_service_conf:
      # client类型，包括brpc, grpc和local_predictor.local_predictor不启动Serving服务，进程内预测
      client_type: local_predictor
      # device_type, 0=cpu, 1=gpu, 2=tensorRT, 3=arm cpu, 4=kunlun xpu
      device_type: 2
      # 计算硬件ID，当devices为""或不写时为CPU预测；当devices为"0", "0,1,2"时为GPU预测，表示使用的GPU卡
      devices: '0'
      # Fetch结果列表，以client_config中fetch_var的alias_name为准, 如果没有设置则全部返回
      fetch_list: ['output_embedding']
      # 模型路径
      model_config: ./serving_server/

      #ir_optim
      ir_optim: True
```


通过docker是可以启动程序的，也没有报错，能访问服务，只是返回的时间，跟没开启trt，差不多
![image](https://user-images.githubusercontent.com/63343847/154634946-4fa3ce3c-127c-4252-b2a2-d55b90a268c7.png)
![image](https://user-images.githubusercontent.com/63343847/154634969-de2b7ec0-aa64-4d33-b4e1-0f2f4d827b1a.png)
